services:
  web:
    build: .
    container_name: watering-system
    restart: unless-stopped
    ports:
      - "5001:5000"
    env_file:
      - .env
    devices:
      - /dev/gpiomem:/dev/gpiomem
    tmpfs:
      - /app/logs
    volumes:
      - watering-data:/app/data
    privileged: true

volumes:
  watering-data:
