services:
  web:
    build: .
    container_name: watering-system
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - GPIO_PIN=17
      - WATERING_DURATION=3
    devices:
      - /dev/gpiomem:/dev/gpiomem
    tmpfs:
      - /app/logs
    volumes:
      - watering-data:/app/data
    privileged: true

volumes:
  watering-data:
